# -------------------------------------------------------------------
# Default Settings
# -------------------------------------------------------------------
#
#
#   Author : PLIQUE Guillaume
#   Version : 1.0

# Basic Informations
version: 'Colifrapy Scaffolder 0.2'
description: 'The Colifrapy Scaffolder is designed to create a new project.'
arguments: 
- [ ['-a', '--author'], {'help' : "Author's name.", "default" : "Author"} ]
- [ ['action'] ]
- [ ['project'] ]